print("_"*40)
print("tugas 1 kelas-b")
print("_"*40)
print("nama : Muhammad Daud Rajas")
print("NPM  : 21083010060")
print("_"*40)
print("Notes;")
print("_"*40)
print("halo dunia")
print("ini adalah script python pertamaku di linux")
